name: Run Gradle on PRs
on:
  push:
    branches: [ testing_jemalloc]
jobs:
  temurin:
    strategy:
      matrix:
        java: [17.0.8+101]
    runs-on: ubuntu-latest
    container:
      image: gcr.io/cache-node/android-builder-jemalloc:0.2
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Execute Gradle build
        run: |
          ./gradlew clean assembleDebug -Dscan.tag.H${{ matrix.java }}-temurin -Dscan.tag.WORKAROUND_AGP_8.2.2_NEW
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_API_KEY }}
          AGENT_JAVA_VERSION: "${{ matrix.java }}-temurin"

