name: CI with GCR Docker Image

on:
  push:
    branches: [ testing_jemalloc]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: cdsap/android-builder-jemalloc:0.3

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
            distribution: temurin
            java-version: 17
      - name: Run a command inside the Docker container
        run: |
          echo ${{ needs.setup-build-environment.outputs.image }}
          echo $HOME
          echo $_GRADLE_VERSION
          echo $PATH
          echo $GRADLE_ZIP
          echo $LD_PRELOAD
          ./gradlew clean assembleRelease -Dscan.tag.H${{ matrix.java }}-temurin -Dscan.tag.WORKAROUND_AGP_8.2.2_NEW
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_API_KEY }}
          AGENT_JAVA_VERSION: "${{ matrix.java }}-temurin"

