name: Run Gradle on PRs
on:
  push:
    branches: [ main3]
jobs:
  temurin:
    strategy:
      matrix:
        java: [21.0.0+35.0.LTS,21.0.1+12.0.LTS,21.0.2+13.0.LTS]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Execute Gradle build
        run: ./gradlew clean assembleDebug -Dscan.tag.H${{ matrix.java }}-temurin -Dscan.tag.WORKAROUND_AGP_8.2.2_NEW
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_API_KEY }}
          AGENT_JAVA_VERSION: "${{ matrix.java }}-temurin"
      - name: Upload test reports
        uses: actions/upload-artifact@v3
        with:
          name: temurin-${{ matrix.java }}
          path: |
            /home/runner/.gradle/caches/transforms-3/acbc84c1395e5a2f9a83686ad10dc90b/transformed/output/jdkImage/lib/*
            /home/runner/.gradle/caches/transforms-3/99b7153d6bdcdd1a2f468c08fa86fa5a/transformed/output/jdkImage/lib/*
            /home/runner/.gradle/caches/transforms-3/de8d13a4ba0c20cc41ac5193e0e632b7/transformed/output/jdkImage/lib/*
            /home/runner/.gradle/caches/transforms-3/df157351579a710139a861ad9f6b742e/transformed/output/jdkImage/lib/*
    continue-on-error: true

  zulu:
    strategy:
      matrix:
        java: [21.0.2+13, 21.0.2+13, 21.0.1+12]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}
      - name: Execute Gradle build
        run: |
             ./gradlew clean assembleDebug -Dscan.tag.H${{ matrix.java }}-zulu -Dscan.tag.WORKAROUND_AGP_8.2.2_NEW
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_API_KEY }}
          AGENT_JAVA_VERSION: "${{ matrix.java }}-zulu"
      - name: Upload test reports
        uses: actions/upload-artifact@v3
        with:
          name: zulu-${{ matrix.java }}
          path: |
            /home/runner/.gradle/caches/transforms-3/df157351579a710139a861ad9f6b742e/transformed/output/jdkImage/lib/*
            /home/runner/.gradle/caches/transforms-3/acbc84c1395e5a2f9a83686ad10dc90b/transformed/output/jdkImage/lib/*
            /home/runner/.gradle/caches/transforms-3/1a2508375073981f50d82e94091c008c/transformed/output/jdkImage/lib/*
            /home/runner/.gradle/caches/transforms-3/70596245383c5ecb7dc62844d764c8fb/transformed/output/jdkImage/lib/*
            /home/runner/.gradle/caches/transforms-3/60f5165b5c883e0c741773a3c887e64f/transformed/output/jdkImage/lib/*
    continue-on-error: true



  liberica:
    strategy:
      matrix:
        java: [21.0.1+12,21.0.2+14]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: liberica
          java-version: ${{ matrix.java }}
      - name: Execute Gradle build
        run: |
            ./gradlew clean assembleDebug -Dscan.tag.H${{ matrix.java }}-liberica -Dscan.tag.WORKAROUND_AGP_8.2.2_NEW
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_API_KEY }}
          AGENT_JAVA_VERSION: "${{ matrix.java }}-liberica"
      - name: Upload test reports
        uses: actions/upload-artifact@v3
        with:
          name: liberica-${{ matrix.java }}
          path: |
            /home/runner/.gradle/caches/transforms-3/ce8b16410f5bb7e4035b0763ac3925bb/transformed/output/jdkImage/lib/*
            /home/runner/.gradle/caches/transforms-3/1a2508375073981f50d82e94091c008c/transformed/output/jdkImage/lib/*
            /home/runner/.gradle/caches/transforms-3/81767170db3f2da71ca4f5ea6a381e33/transformed/output/jdkImage/lib/*
            /home/runner/.gradle/caches/transforms-3/8dcebbfbf0b5316d7855ce586e2654f1/transformed/output/jdkImage/lib/*
            /home/runner/.gradle/caches/transforms-3/a02e8e48a19429a1c861c4e8186e0153/transformed/output/jdkImage/lib/*
            /home/runner/.gradle/caches/transforms-3/b95d1bed050faa15462a0015647f55d1/transformed/output/jdkImage/lib/*
    continue-on-error: true
